/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;
import BackEnd.CourseDB;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class ApprovedCourses extends javax.swing.JPanel {

    /**
     * Creates new form ApprovedCourses
     */
    public ApprovedCourses() {
        initComponents();
        setBackground(Color.LIGHT_GRAY);

        // Load approved courses
        ArrayList<Course> allCourses = new CourseDB("courses.json").load();
        populateTable(allCourses);
        
        
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            String courseId = jTable1.getValueAt(row, 0).toString();
            String courseName = jTable1.getValueAt(row, 1).toString();

            // Show confirmation dialog
            int option = javax.swing.JOptionPane.showOptionDialog(
                null,
                "Choose an action for this course:" + courseName + "?",
                "Course Action",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"PENDING", "REJECT"},
                "APPROVE"
            );

            if (option == 0) {
                updateCourseStatus(courseId, "PENDING");
                javax.swing.JOptionPane.showMessageDialog(null, courseName + " is now PENDING !");
            } else if (option == 1) { 
                updateCourseStatus(courseId, "REJECTED");
                javax.swing.JOptionPane.showMessageDialog(null, courseName + "has been REJECTED!");
            }

            refresh();
        }
    }
});  
    }
    private void updateCourseStatus(String courseId, String newStatus) {
    ArrayList<Course> allCourses = new CourseDB("courses.json").load();
    for (Course c : allCourses) {
        if (c.getCourseId().equals(courseId)) {
            c.setStatus(newStatus);
            break;
        }
    }

    new CourseDB("courses.json").save(allCourses);
}
        
        
        
        
        
        
        
        
        
        
    
public void populateTable(ArrayList<Course> courses) {
    String[] columns = {"Course ID", "Course Name", "Instructor ID", "Description"};
    DefaultTableModel model = new DefaultTableModel(columns, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // make table read-only
        }
    };

    for (Course c : courses) {
        if ("APPROVED".equalsIgnoreCase(c.getStatus())) {
            model.addRow(new Object[]{
                c.getCourseId(),
                c.getTitle(),
                c.getInstructorId(),
                c.getDescription()
            });
        }
    }

    jTable1.setModel(model);
}

// Refresh the table (call this when a new course is approved)
public void refresh() {
    ArrayList<Course> allCourses = new CourseDB("courses.json").load(); // returns ArrayList<Course>
    populateTable(allCourses);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(980, 750));

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 750));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
