/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import BackEnd.Certificate;
import BackEnd.Srudent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Dell
 */

public class CertificatePanel extends javax.swing.JPanel {

    private Certificate cert;
private Srudent loggedStudent;
    /**
     * Creates new form CertificatePanel
     */
    public CertificatePanel() {
        initComponents();
    }
   public CertificatePanel(Certificate cert, Srudent loggedStudent) {
    this.cert = cert;
    this.loggedStudent = loggedStudent;
    initComponents();
    loadCertificateData();
}
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCertId = new javax.swing.JLabel();
        lblStudentId = new javax.swing.JLabel();
        lblCourseId = new javax.swing.JLabel();
        lblIssueDate = new javax.swing.JLabel();
        btnDownload = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setForeground(new java.awt.Color(0, 153, 153));

        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        lblCertId.setText("CertId");

        lblStudentId.setText("StudentId");

        lblCourseId.setText("CourseId");

        lblIssueDate.setText("IssueDate");

        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIssueDate)
                    .addComponent(lblCertId)
                    .addComponent(lblStudentId)
                    .addComponent(lblCourseId))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btnDownload)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblCertId)
                .addGap(18, 18, 18)
                .addComponent(lblCourseId)
                .addGap(29, 29, 29)
                .addComponent(lblStudentId)
                .addGap(27, 27, 27)
                .addComponent(lblIssueDate)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnDownload))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           // Get the MainFrame window
    MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);

    // Load the student dashboard again
    StudentDashBoard dashboard = new StudentDashBoard(loggedStudent.getUsername());

    // Switch screen
    mainFrame.setContentPane(dashboard);
    mainFrame.revalidate();
    mainFrame.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
     try {
    // File name
    String filename = "certificate_" + cert.getCertificateId() + ".pdf";

    // Create PDF
    com.itextpdf.text.Document pdfDoc = new com.itextpdf.text.Document();
    com.itextpdf.text.pdf.PdfWriter.getInstance(pdfDoc, new java.io.FileOutputStream(filename));

    pdfDoc.open();

    // Title
    com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(
            com.itextpdf.text.Font.FontFamily.HELVETICA, 20, com.itextpdf.text.Font.BOLD);
    pdfDoc.add(new com.itextpdf.text.Paragraph("Certificate of Completion", titleFont));
    pdfDoc.add(new com.itextpdf.text.Paragraph("\n"));

    // Content
    pdfDoc.add(new com.itextpdf.text.Paragraph("Certificate ID : " + cert.getCertificateId()));
    pdfDoc.add(new com.itextpdf.text.Paragraph("Student ID     : " + cert.getStudentId()));
    pdfDoc.add(new com.itextpdf.text.Paragraph("Course ID      : " + cert.getCourseId()));
    pdfDoc.add(new com.itextpdf.text.Paragraph("Issue Date     : " + cert.getIssueDate()));

    pdfDoc.close();

    // Show success message
    JOptionPane.showMessageDialog(this,
            "Certificate saved as:\n" + filename,
            "Download Successful",
            JOptionPane.INFORMATION_MESSAGE);

} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this,
            "Error downloading certificate.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnDownloadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCertId;
    private javax.swing.JLabel lblCourseId;
    private javax.swing.JLabel lblIssueDate;
    private javax.swing.JLabel lblStudentId;
    // End of variables declaration//GEN-END:variables
private void loadCertificateData() {
    lblCertId.setText("Certificate ID: " + cert.getCertificateId());
    lblStudentId.setText("Student ID: " + cert.getStudentId());
    lblCourseId.setText("Course ID: " + cert.getCourseId());
    lblIssueDate.setText("Issue Date: " + cert.getIssueDate());
}
private void downloadCertificate() {

}
}
