/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;
import BackEnd.CourseDB;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class PendingCourses extends javax.swing.JPanel {

    
    private JTable table;

    public PendingCourses() {
            initComponents();
            CourseDB courseDB = new CourseDB("courses.json");
            List<Course> courses = courseDB.load();
    setBackground(Color.LIGHT_GRAY);

    if (courses == null) {
        courses = new CourseDB("courses.json").load();
    }

    populateTable(courses);
    
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            String courseId = jTable1.getValueAt(row, 0).toString();
            String courseName = jTable1.getValueAt(row, 1).toString();

            // Show confirmation dialog
            int option = javax.swing.JOptionPane.showOptionDialog(
                null,
                "Do you want to APPROVE or REJECT the course: " + courseName + "?",
                "Course Approval",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"APPROVE", "REJECT"},
                "APPROVE"
            );

            if (option == 0) { // APPROVE
                updateCourseStatus(courseId, "APPROVED");
                javax.swing.JOptionPane.showMessageDialog(null, courseName + " has been APPROVED!");
            } else if (option == 1) { // REJECT
                updateCourseStatus(courseId, "REJECTED");
                javax.swing.JOptionPane.showMessageDialog(null, courseName + " has been REJECTED!");
            }

            // Refresh the table to remove/update pending courses
            refreshTable();
        }
    }
});  
    }
    private void updateCourseStatus(String courseId, String newStatus) {
    ArrayList<Course> allCourses = new CourseDB("courses.json").load();
    for (Course c : allCourses) {
        if (c.getCourseId().equals(courseId)) {
            c.setStatus(newStatus);
            break;
        }
    }
    // Save back to the JSON file
    new CourseDB("courses.json").save(allCourses);
}
private void refreshTable() {
    List<Course> allCourses = new CourseDB("courses.json").load();
    populateTable(allCourses);
}

    private void populateTable(List<Course> courses) {
        String[] columns = {"Course ID", "Course Name", "Instructor ID", "Description"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        for (Course c : courses) {
            if ("PENDING".equals(c.getStatus())) {
                model.addRow(new Object[]{
                    c.getCourseId(),
                    c.getTitle(),
                    c.getInstructorId(),
                    c.getDescription()
                });
            }
        }

        jTable1.setModel(model);
    }


        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(980, 750));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
