/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
/**
 *
 * @author Mohamed
 */
public class QuizAverage extends javax.swing.JFrame {
        private ArrayList<Double> averages;
    private ArrayList<String> lessonTitles;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuizAverage.class.getName());

    /**
     * Creates new form QuizAverage
     */
     public QuizAverage() {
        initComponents();
    }
    public QuizAverage(ArrayList<Double> averages, ArrayList<String> lessonTitles) {
    this.averages = averages;
    this.lessonTitles = lessonTitles;

    setTitle("Quiz Average per Lesson");
    setSize(800, 600);
    setLocationRelativeTo(null);
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    // Use BorderLayout instead of GroupLayout
    setLayout(new BorderLayout());

    // Add the chart panel
    add(createChartPanel(), BorderLayout.CENTER);
}

    private JPanel createChartPanel() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (int i = 0; i < averages.size(); i++) {
            dataset.addValue(averages.get(i), "Average Score", lessonTitles.get(i));
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Quiz Average per Lesson",
                "Lesson",
                "Average Score",
                dataset,
                PlotOrientation.VERTICAL,
                false, true, false
        );

        return new ChartPanel(chart);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
