/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;
import BackEnd.CourseDB;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class RejectedCourses extends javax.swing.JPanel {

    /**
     * Creates new form RejectedCourses
     */
 

    private Utility util;

    public RejectedCourses() {
        initComponents();
        setBackground(Color.LIGHT_GRAY);

        util = new Utility(jTable2);
        util.refresh("REJECTED");

        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                int row = jTable2.getSelectedRow();
                if (row < 0) return;

                String courseId = jTable2.getValueAt(row, 0).toString();
                String courseName = jTable2.getValueAt(row, 1).toString();

                int option = JOptionPane.showOptionDialog(
                        null,
                        "Restore course: " + courseName,
                        "Course Action",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        new Object[]{"PENDING", "APPROVE"},
                        "PENDING"
                );

                if (option == 0) {
                    util.updateCourseStatus(courseId, "PENDING");
                    JOptionPane.showMessageDialog(null, courseName + " moved to PENDING!");
                } else if (option == 1) {
                    util.updateCourseStatus(courseId, "APPROVED");
                    JOptionPane.showMessageDialog(null, courseName + " APPROVED!");
                }

                util.refresh("REJECTED");
            }
        });
    }


    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(980, 750));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(980, 750));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setPreferredSize(new java.awt.Dimension(980, 750));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
