/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;
import BackEnd.CourseDB;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class RejectedCourses extends javax.swing.JPanel {

    /**
     * Creates new form RejectedCourses
     */
    public RejectedCourses() {
        initComponents();
        setBackground(Color.LIGHT_GRAY);

        // Load rejected courses
        ArrayList<Course> allCourses = new CourseDB("courses.json").load();
        populateTable(allCourses);
        
        
            jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = jTable2.getSelectedRow();
        if (row >= 0) {
            String courseId = jTable2.getValueAt(row, 0).toString();
            String courseName = jTable2.getValueAt(row, 1).toString();

            // Show confirmation dialog
            int option = javax.swing.JOptionPane.showOptionDialog(
                null,
                "Choose an action for this course:" + courseName + "?",
                "Course Action",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"APPROVE", "PENDING"},
                "APPROVE"
            );

            if (option == 0) {
                updateCourseStatus(courseId, "APPROVED");
                javax.swing.JOptionPane.showMessageDialog(null, courseName + " has been APPROVED!");
            } else if (option == 1) { 
                updateCourseStatus(courseId, "PENDING");
                javax.swing.JOptionPane.showMessageDialog(null, courseName + " is now PENDING !");
            }

            refresh();
        }
    }
});  
    }
    private void updateCourseStatus(String courseId, String newStatus) {
    ArrayList<Course> allCourses = new CourseDB("courses.json").load();
    for (Course c : allCourses) {
        if (c.getCourseId().equals(courseId)) {
            c.setStatus(newStatus);
            break;
        }
    }

    new CourseDB("courses.json").save(allCourses);
}
        
        
        
        
    

    public void populateTable(ArrayList<Course> courses) {
        String[] columns = {"Course ID", "Course Name", "Instructor ID", "Description"};
        DefaultTableModel model = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        for (Course c : courses) {
            if ("REJECTED".equalsIgnoreCase(c.getStatus())) {
                model.addRow(new Object[]{
                    c.getCourseId(),
                    c.getTitle(),
                    c.getInstructorId(),
                    c.getDescription()
                });
            }
        }

        jTable2.setModel(model);
    }


    public void refresh() {
        ArrayList<Course> allCourses = new CourseDB("courses.json").load();
        populateTable(allCourses);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(980, 750));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(980, 750));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setPreferredSize(new java.awt.Dimension(980, 750));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
