/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;
import BackEnd.*;
import java.awt.*;
import javax.swing.*;
import java.util.ArrayList;
/**
 *
 * @author Asus
 */
public class StudentDashBoard extends javax.swing.JPanel {
private CourseDB courseDB = new CourseDB("courses.json");
private StudentDB studentDB = new StudentDB("users.json");

private DefaultListModel<Course> availableModel = new DefaultListModel<>();
private DefaultListModel<Course> enrolledModel = new DefaultListModel<>();
private DefaultListModel<Lesson> lessonModel = new DefaultListModel<>();

private ArrayList<Srudent> studentsList = studentDB.load();
private Srudent loggedStudent;

private JList<Course> listAvailable;
private JList<Course> listEnrolled;
private JList<Lesson> listLessons;

private Course selectedCourse;
private Lesson selectedLesson;

private String username;
private String loggedStudentId;
    
    /**
     * Creates new form StudentDashBoard
     */
    public StudentDashBoard(String username) {
        this.username = username;

for (Srudent s : studentsList) {
    if (s.getUsername().trim().equals(username)) {
        loggedStudent = s;
        loggedStudentId = s.getUserId();
        break;
    }
}

initComponents();

listAvailable = new JList<>(availableModel);
listEnrolled = new JList<>(enrolledModel);
listLessons = new JList<>(lessonModel);

panelAvailable.setLayout(new BorderLayout());
panelAvailable.add(new JScrollPane(listAvailable), BorderLayout.CENTER);

panelEnrolled.setLayout(new BorderLayout());
panelEnrolled.add(new JScrollPane(listEnrolled), BorderLayout.CENTER);

panelLessons.setLayout(new BorderLayout());
panelLessons.add(new JScrollPane(listLessons), BorderLayout.CENTER);

// selecting a course loads lessons
listEnrolled.addListSelectionListener(e -> {
    selectedCourse = listEnrolled.getSelectedValue();
    loadLessons();
});

loadCourses();
    }
    private void loadCourses() {
        availableModel.clear();
    enrolledModel.clear();

    ArrayList<Course> courses = courseDB.load();

    for (Course c : courses) {
        if (c.getStudents().contains(loggedStudentId)) {
            enrolledModel.addElement(c);
        } else {
            availableModel.addElement(c);
        }
    }

    lessonModel.clear();
    selectedCourse = null;
    }
    
    private void loadLessons() {
         lessonModel.clear();
    if (selectedCourse == null) return;

    for (Lesson l : selectedCourse.getLessons()) {
        lessonModel.addElement(l);
    }
    updateProgress();
    }

    private void enrollInCourse() {
         Course sel = listAvailable.getSelectedValue();

    if (sel == null) {
        JOptionPane.showMessageDialog(this, "Select a course first.");
        return;
    }

    ArrayList<Course> all = courseDB.load();
    for (Course c : all) {
        if (c.getCourseId().equals(sel.getCourseId())) {
            c.enrollStudent(loggedStudentId);
    
    for (Srudent s : studentsList){
        if (s.getUserId().equals(loggedStudentId)){
            s.enrollCourse(sel.getCourseId());
        }
    }
            
        }
    }

    courseDB.save(all);
    studentDB.save(studentsList);
    
    loadCourses();
    }

    private void updateProgress() {
    if (selectedCourse == null) {
        lblProgress.setText("Progress: 0%");
        return;
    }

    int totalLessons = selectedCourse.getLessons().size();

    int completed = 0;
    for (Lesson lesson : selectedCourse.getLessons()) {
        if (loggedStudent.getCompletedLessons().contains(lesson.getLessonId())) {
            completed++;
        }
    }

    int percent = (totalLessons == 0) ? 0 : (completed * 100 / totalLessons);

    lblProgress.setText("Progress: " + percent + "%");
}


    private void viewLessonContent() {
       Lesson selectedLesson = listLessons.getSelectedValue();
    if (selectedLesson == null) {
        JOptionPane.showMessageDialog(this, "Select a Lesson first.");
        return;
    }
        JOptionPane.showMessageDialog(this,selectedLesson.getContent());
  
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentDashBoard = new javax.swing.JPanel();
        panelAvailable = new javax.swing.JPanel();
        panelEnrolled = new javax.swing.JPanel();
        panelLessons = new javax.swing.JPanel();
        btnEnroll = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnViewLessons = new javax.swing.JButton();
        btnMarkComplete = new javax.swing.JButton();
        lblProgress = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ViewLessonContent = new javax.swing.JButton();
        btnTakeQuiz = new javax.swing.JButton();

        StudentDashBoard.setBackground(new java.awt.Color(0, 0, 0));
        StudentDashBoard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StudentDashBoard.setPreferredSize(new java.awt.Dimension(439, 378));

        javax.swing.GroupLayout panelAvailableLayout = new javax.swing.GroupLayout(panelAvailable);
        panelAvailable.setLayout(panelAvailableLayout);
        panelAvailableLayout.setHorizontalGroup(
            panelAvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        panelAvailableLayout.setVerticalGroup(
            panelAvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelEnrolledLayout = new javax.swing.GroupLayout(panelEnrolled);
        panelEnrolled.setLayout(panelEnrolledLayout);
        panelEnrolledLayout.setHorizontalGroup(
            panelEnrolledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        panelEnrolledLayout.setVerticalGroup(
            panelEnrolledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLessonsLayout = new javax.swing.GroupLayout(panelLessons);
        panelLessons.setLayout(panelLessonsLayout);
        panelLessonsLayout.setHorizontalGroup(
            panelLessonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        panelLessonsLayout.setVerticalGroup(
            panelLessonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        btnEnroll.setBackground(new java.awt.Color(255, 102, 0));
        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(255, 102, 0));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnViewLessons.setBackground(new java.awt.Color(255, 102, 0));
        btnViewLessons.setText("view lessons");
        btnViewLessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLessonsActionPerformed(evt);
            }
        });

        btnMarkComplete.setBackground(new java.awt.Color(255, 102, 0));
        btnMarkComplete.setText("Mark Completed");
        btnMarkComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkCompleteActionPerformed(evt);
            }
        });

        lblProgress.setBackground(new java.awt.Color(255, 102, 0));
        lblProgress.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProgress.setForeground(new java.awt.Color(255, 102, 0));
        lblProgress.setText("progress : 0%");

        btnLogOut.setBackground(new java.awt.Color(255, 102, 0));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Available Courses");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Enrolled Courses");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Lessons");

        ViewLessonContent.setBackground(new java.awt.Color(255, 102, 0));
        ViewLessonContent.setText("View lesson Content");
        ViewLessonContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLessonContentActionPerformed(evt);
            }
        });

        btnTakeQuiz.setBackground(new java.awt.Color(255, 102, 0));
        btnTakeQuiz.setText("Take Quiz");
        btnTakeQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakeQuizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentDashBoardLayout = new javax.swing.GroupLayout(StudentDashBoard);
        StudentDashBoard.setLayout(StudentDashBoardLayout);
        StudentDashBoardLayout.setHorizontalGroup(
            StudentDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentDashBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentDashBoardLayout.createSequentialGroup()
                        .addGroup(StudentDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentDashBoardLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addGap(179, 179, 179))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentDashBoardLayout.createSequentialGroup()
                                .addComponent(panelAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelEnrolled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(StudentDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelLessons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StudentDashBoardLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentDashBoardLayout.createSequentialGroup()
                        .addGroup(StudentDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(StudentDashBoardLayout.createSequentialGroup()
                                .addGroup(StudentDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(StudentDashBoardLayout.createSequentialGroup()
                                        .addComponent(btnRefresh)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMarkComplete)
                                        .addGap(32, 32, 32)
                                        .addComponent(lblProgress)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTakeQuiz))
                            .addGroup(StudentDashBoardLayout.createSequentialGroup()
                                .addComponent(btnEnroll)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewLessons)
                                .addGap(79, 79, 79)
                                .addComponent(btnLogOut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewLessonContent)))
                        .addGap(58, 58, 58))))
        );
        StudentDashBoardLayout.setVerticalGroup(
            StudentDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentDashBoardLayout.createSequentialGroup()
                .addGroup(StudentDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelLessons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEnrolled, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StudentDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(StudentDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnroll)
                    .addComponent(btnViewLessons)
                    .addComponent(btnLogOut)
                    .addComponent(ViewLessonContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarkComplete)
                    .addComponent(btnRefresh)
                    .addComponent(lblProgress)
                    .addComponent(btnTakeQuiz))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentDashBoard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
            loadCourses();

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        // TODO add your handling code here:
        enrollInCourse();
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnViewLessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLessonsActionPerformed
        // TODO add your handling code here:
        selectedCourse = listEnrolled.getSelectedValue();
        selectedCourse = listAvailable.getSelectedValue();
    
    if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this, "Select a course first.");
        return;
    }

    loadLessons();
    }//GEN-LAST:event_btnViewLessonsActionPerformed

    private void btnMarkCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkCompleteActionPerformed
        // TODO add your handling code here:
        Lesson selectedLesson = listLessons.getSelectedValue();
        Course selectedCourse = listEnrolled.getSelectedValue();

    if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this, "Select the appropriate  course first.");
        return;
    }

    if (selectedLesson == null) {
        JOptionPane.showMessageDialog(this, "Select a lesson first.");
        return;
    }

  
if (!loggedStudent.getEnrolledCourses().contains(selectedCourse.getCourseId())) {
        JOptionPane.showMessageDialog(this,
                "You cannot complete lessons for a course you are NOT enrolled in!");
        return;
    }

    ArrayList<Srudent> allStudents = studentDB.load();
    for (Srudent s : allStudents) {
        if (s.getUserId().equals(loggedStudentId)) {
            s.completeLesson(selectedLesson.getLessonId());
        }
    }


    loggedStudent.completeLesson(selectedLesson.getLessonId());
    
    studentDB.save(allStudents);
    updateProgress();
    
    JOptionPane.showMessageDialog(this, "Lesson marked as completed!");
    }//GEN-LAST:event_btnMarkCompleteActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
//       JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
      MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);

   
    mainFrame.setContentPane(new LogIn());  
    mainFrame.setSize(400, 500);
    mainFrame.setLocationRelativeTo(null); 

    mainFrame.revalidate();
    mainFrame.repaint();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void ViewLessonContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLessonContentActionPerformed
        // TODO add your handling code here:
        viewLessonContent();
    }//GEN-LAST:event_ViewLessonContentActionPerformed

    private void btnTakeQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakeQuizActionPerformed
        // TODO add your handling code here:
        selectedLesson = listLessons.getSelectedValue();
        selectedCourse = listEnrolled.getSelectedValue();

    if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this, "Select a course first.");
        return;
    }

    if (selectedLesson == null) {
        JOptionPane.showMessageDialog(this, "Select a lesson first.");
        return;
    }

    // Open QuizPanel inside MainFrame
    MainFrame frame = (MainFrame) SwingUtilities.getWindowAncestor(this);
    frame.setContentPane(new Quiz(selectedLesson, loggedStudent, selectedCourse));
    frame.revalidate();
    frame.repaint();
    }//GEN-LAST:event_btnTakeQuizActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudentDashBoard;
    private javax.swing.JButton ViewLessonContent;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMarkComplete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTakeQuiz;
    private javax.swing.JButton btnViewLessons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JPanel panelAvailable;
    private javax.swing.JPanel panelEnrolled;
    private javax.swing.JPanel panelLessons;
    // End of variables declaration//GEN-END:variables
}
